myproject/temp/objects/Participant__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myproject/temp/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Due Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

myproject/temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Overdue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Overdue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Participant__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Participant__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                    <default>true</default>
                    <label>Low</label>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Waiting on someone else</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PTask</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

myproject/temp/objects/Task_Followup__c.object
<CustomObject>
    <fields>
        <fullName>MasterTask__c</fullName>
        <label>MasterTask</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Task Followups</relationshipLabel>
        <relationshipName>Task_Followups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Task Followups</relationshipLabel>
        <relationshipName>Task_Followups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Task Followup</label>
    <nameField>
        <label>Task Followup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Followups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

myproject/force-app/main/default/classes/KanbanKontroller.cls
public class KanbanKontroller {
	@AuraEnabled
    public static List<Task__c> getTasks(Id RecordId){
        return [SELECT Id, Name, Project__c, Project__r.Name, Priority__c, Status__c, Participant__r.User__r.MediumPhotoUrl, Participant__r.User__r.Name, Start_Date__c, End_Date__c, Overdue__c FROM Task__c WHERE Project__c = :RecordId];
    }
    
    @AuraEnabled
    public static void updateTasks(String taskdesc, String TaskId){
        Id daId = Id.valueOf(TaskId);
        Task__c tasktoUpdate = [SELECT Id, Status__c FROM Task__c WHERE Id = :daId];
        tasktoUpdate.Status__c = taskdesc;
        update tasktoUpdate;
    }
    
    @AuraEnabled
    public static void updatedaTask(Task__c taske){
        update taske;
    }
    
    @AuraEnabled
    public static void deleteTask(Task__c taske){
        List<Task_Followup__c> followups = [SELECT Id, Name FROM Task_Followup__c WHERE MasterTask__c = :taske.Id];
        Task__c tasktodel = [SELECT Id, Name FROM Task__c WHERE Id = :taske.Id ];
        delete followups;
        delete tasktodel;
    }
    
    @AuraEnabled
    public static List<Task_Followup__c> getFollowups(Task__c task){
        return [SELECT Id, Name FROM Task_Followup__c WHERE MasterTask__c = :task.Id];
    }
    
    @AuraEnabled
    public static Task__c getdaTask(String taskId){
        Id daId = Id.valueOf(TaskId);
        return [SELECT Id, Name,
                Project__c,
                Project__r.Name,
                Priority__c,
                Status__c,
                Participant__r.User__r.MediumPhotoUrl,
                Participant__r.User__R.Name,
                Start_Date__c,
                End_Date__c FROM Task__c WHERE Id = :daId];
    }
    
    public class KanbanWrap{
        @AuraEnabled
        List<Task__c> Tasks {get;set;}
        @AuraEnabled
        List<String> pickVals {get;set;}
        
        public kanbanWrap(List<Task__c> tasks, List<String> pVals){
            this.Tasks = tasks;
            this.pickVals = pVals;
        }
    }
}