myproject/temp/objects/Participant__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myproject/temp/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

myproject/temp/objects/Project_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Costs</relationshipLabel>
        <relationshipName>Project_Costs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Project Cost</label>
    <nameField>
        <label>Project Cost Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myproject/temp/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myproject/temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Participant__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Participant__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PTask</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

myproject/temp/objects/Task_Followup__c.object
<CustomObject>
    <fields>
        <fullName>MasterTask__c</fullName>
        <label>MasterTask</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Task Followups</relationshipLabel>
        <relationshipName>Task_Followups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Task Followups</relationshipLabel>
        <relationshipName>Task_Followups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task Followup</label>
    <nameField>
        <label>Task Followup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Followups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

myproject/force-app/main/default/classes/Infocontroller.cls
public class Infocontroller {
	@AuraEnabled
    public static void deleteProject(Id RecordId){
        Project__c proj = [SELECT Id, Name, OwnerId FROM Project__c WHERE Id = :RecordId];
        if(UserInfo.getUserId() == proj.OwnerId){
            List<Task__c> tasks = [SELECT Id, Name FROM Task__c WHERE Project__c = :RecordId];
            List<Sprint__c> sprints = [SELECT Id, Name FROM Sprint__c WHERE Project__c = :RecordId];
            List<Task_Followup__c> followups = [SELECT Id, Name FROM Task_Followup__c WHERE MasterTask__r.Project__c = :RecordId];
            List<Participant__c> participants = [SELECT Id, Name FROM Participant__c WHERE Project__c = :RecordId];
            List<Project_Cost__c> costs = [SELECT Id, Name FROM Project_Cost__c WHERE Project__c = :RecordId];
            try{
                delete followups;
                delete costs;
                delete tasks;
                delete sprints;
                delete participants;
                delete proj;
            }
            catch(Dmlexception e){
                throw new AuraHandledException('Error Exception happend'+e.getDmlMessage(0));
            }
        }
        else{
            throw new AuraHandledException('You are not the owner');
        }
    }
}