myproject/temp/objects/Participant__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myproject/temp/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Due Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

myproject/temp/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EstHours__c</fullName>
        <label>EstHours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Finished</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkHours__c</fullName>
        <label>WorkHours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myproject/temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Participant__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Participant__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                    <default>true</default>
                    <label>Low</label>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Waiting on someone else</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PTask</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

myproject/temp/classes/AgileKanbanController2.cls
public class AgileKanbanController2 {
	@AuraEnabled
    public static List<Task__c> getTasks(Id RecordId){
        return [SELECT Id, Name, Project__c, Project__r.Name, Priority__c, Sprint__c, Participant__r.User__r.MediumPhotoUrl, Participant__r.User__r.Name, Start_Date__c, End_Date__c FROM Task__c WHERE Project__c = :RecordId];
    }
    
    @AuraEnabled
    public static void newSprinte(Id RecordId,Integer num){
        Integer nume = num + 1;
        Sprint__c newSpri = new Sprint__c(Name='Sprint ' + nume,Status__c = 'Inactive',Project__c = RecordId);
        insert newSpri;
    }
    
        @AuraEnabled
    public static void updatedaTask(Task__c taske){
        update taske;
    }
    
    @AuraEnabled
    public static void deleteTask(Task__c taske){
        Task__c tasktodel = [SELECT Id, Name FROM Task__c WHERE Id = :taske.Id ];
        delete tasktodel;
    }
    
    @AuraEnabled
    public static void completeSprinte(Sprint__c Sprinte){
        Sprinte.Status__c = 'Finished';
        update Sprinte;
    }
    
    @AuraEnabled
    public static List<Sprint__c> getSprints2(Id RecordId){
        return [SELECT Id, Name, Status__c, EstHours__c, WorkHours__c FROM Sprint__c WHERE Project__c = :RecordId ORDER BY Name];
    }
    
    @AuraEnabled
    public static void updateTasks(String taskdesc, String TaskId){
        Id daId = Id.valueOf(TaskId);
        Task__c tasktoUpdate = [SELECT Id, Status__c FROM Task__c WHERE Id = :daId];
        tasktoUpdate.Status__c = taskdesc;
        update tasktoUpdate;
    }
    
    @AuraEnabled
    public static void updateTasks2(String taskdesc, String TaskId){
        if(taskdesc != null){
            Id daId = Id.valueOf(TaskId);
            Id sprintId = Id.valueOf(taskdesc);
            Task__c tasktoUpdate = [SELECT Id, Sprint__c FROM Task__c WHERE Id = :daId];
            tasktoUpdate.Sprint__c = sprintId;
            update tasktoUpdate;
        }
        else{
            Id daId = Id.valueOf(TaskId);
            Task__c tasktoUpdate = [SELECT Id, Sprint__c FROM Task__c WHERE Id = :daId];
            tasktoUpdate.Sprint__c = null;
            update tasktoUpdate;
        }
    }
    
    @AuraEnabled
    public static Task__c getdaTask(String taskId){
        Id daId = Id.valueOf(TaskId);
        return [SELECT Id, Name,
                Project__c,
                Project__r.Name,
                Priority__c,
                Status__c,
                Participant__r.User__r.MediumPhotoUrl,
                Participant__r.User__r.Name,
                Description__c,
                Start_Date__c,
                End_Date__c FROM Task__c WHERE Id = :daId];
    }
    
    public class KanbanWrap{
        @AuraEnabled
        List<Task__c> Tasks {get;set;}
        @AuraEnabled
        List<String> pickVals {get;set;}
        
        public kanbanWrap(List<Task__c> tasks, List<String> pVals){
            this.Tasks = tasks;
            this.pickVals = pVals;
        }
    }
}