myproject/temp/objects/Participant__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myproject/temp/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

myproject/temp/classes/FlowApex.cls
public class FlowApex {
	@InvocableMethod
    public static List<CollaborationGroup> findGroup(List<Participant__c> Participants){
        List<Id> ParIds = new List<Id>();
        for(Participant__c par : Participants){
            ParIds.add(par.Id);
        }
        List<Participant__c> detailedLst = [SELECT Id, Name, Project__r.Id FROM Participant__c WHERE Id IN :ParIds];
        List<Id> ProjectIds = new List<Id>();
        for(Participant__c proj : detailedLst){
            ProjectIds.add(proj.Project__r.Id);
        }
        List<CollaborationGroupRecord> GroupRecords = [SELECT Id, CollaborationGroupId FROM CollaborationGroupRecord];
        List<Id> GroupIds = new List<Id>();
        for(CollaborationGroupRecord groupre : GroupRecords){
            GroupIds.add(groupre.CollaborationGroupId);
        }
        return [SELECT Id, Name FROM CollaborationGroup WHERE Id IN :GroupIds];
    }
}