myproject/temp/objects/PComment__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>PComments</relationshipLabel>
        <relationshipName>PComments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PComments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PComment</label>
    <nameField>
        <displayFormat>PCOMM-{0000}</displayFormat>
        <label>PComment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PComments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myproject/temp/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

myproject/temp/classes/feedcreatorcontrol.cls
public class feedcreatorcontrol {
    @AuraEnabled
    public static List<PComment__c> getFeeds(Id ProjectId){
        return [SELECT Id, Name, Comment__c, Date__c, User__c, User__r.Name FROM PComment__c WHERE Project__c = :ProjectId];
    }
    
	@AuraEnabled
    public static void createFeed(PComment__c comment,Id ProjectId, Date today){
        comment.Project__c = ProjectId;
        comment.Date__c = today;
        comment.User__c = userInfo.getUserId();
        insert comment;
    }
}