myproject/temp/objects/PEvent__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Pevents</relationshipLabel>
        <relationshipName>Pevents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PEvent</label>
    <nameField>
        <label>PEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pevents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myproject/temp/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Due Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

myproject/temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Overdue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Overdue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>PTask</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

myproject/force-app/main/default/classes/CalendarController2.cls
public class CalendarController2 {
	@AuraEnabled
    public static List<Task__c> getTasks(Id RecordId){
        List<Task__c> result =  [Select Id, Name,End_Date__c, Start_Date__c,LastModifiedDate from Task__c Where Project__c = :RecordId
                                 AND Overdue__c = False];
        return result ; 
    } 
    @AuraEnabled
    public static List<PEvent__c> getEvents(Id RecordId){
        List<PEvent__c> result =  [Select Id, Name, Date__c from PEvent__c where Project__c = :RecordId];
        return result ; 
    } 
}