myproject/temp/objects/PEvent__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <label>PEvent</label>
    <nameField>
        <label>PEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pevents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myproject/temp/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>PTask</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

myproject/temp/classes/calendarControl.cls
public class calendarControl {
	@AuraEnabled
    public static List<Task__c> getTasks(){
        List<Task__c> result =  [Select Id, Name,End_Date__c, Start_Date__c,LastModifiedDate from Task__c ];
        return result ; 
    } 
    
    @AuraEnabled
    public static List<PEvent__c> getEvents(){
        List<PEvent__c> result =  [Select Id, Name, Date__c from PEvent__c ];
        return result ; 
    } 
}