myproject/temp/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

myproject/temp/classes/ClientController.cls
public class ClientController {
	@AuraEnabled
    public static String createClient(Contact client, Id RecordId){
        try{
        Contact a = new Contact(FirstName = client.FirstName,
                                LastName = client.LastName,
                                Email = Client.Email,
                                Phone = Client.Phone);
		Project__c proj = [SELECT Id, Name, Client__c FROM Project__c WHERE Id = :RecordId];
        insert a;
        proj.Client__c = a.Id;
        update proj;
        }
        catch(DmlException e){
            return 'Some error happened';
        }
        return null;
        
    }
    
    
}