myproject/temp/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EstHours__c</fullName>
        <label>EstHours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FinishDate__c</fullName>
        <label>FinishDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WorkHours__c</fullName>
        <label>WorkHours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myproject/temp/classes/setWorkHour.cls
public class setWorkHour {
	@InvocableMethod
    public static void setWH(List<Sprint__c> sprints){//method to be called by process builder
        List<Id> sprIds = new List<Id>();
        for(Sprint__c sprint : sprints){
            sprIds.add(sprint.Id);
        }
        List<Sprint__c> fullsprints = [SELECT Id, Name, Start_Date__c, End_Date__c, FinishDate__c, WorkHours__c FROM Sprint__c WHERE Id IN: sprIds];
        for(Sprint__c sprint : fullsprints){
            sprint.EstHours__c = Decimal.valueOf((sprint.End_Date__c.getTime() - sprint.Start_Date__c.getTime())/3600000);
            sprint.WorkHours__c = Decimal.valueOf((sprint.FinishDate__c.getTime() - sprint.Start_Date__c.getTime())/3600000);
        }
        update fullsprints;
    }
}