myproject/temp/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Finished</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myproject/temp/classes/SprintFlowApex.cls
public class SprintFlowApex {
	@InvocableMethod
    public static void keepOneActive(List<Sprint__c> Sprints){
        List<Id> inputIds = new List<Id>();
        for(Sprint__c sprint : Sprints){
            inputIds.add(sprint.Id);
        }
        List<Sprint__c> otherActiveSprints = [SELECT Id, Name, Status__c FROM Sprint__c WHERE NOT(Id IN :inputIds)];
        for(Sprint__c activeSprint : otherActiveSprints){
            if(activeSprint.Status__c == 'Active'){
                activeSprint.Status__c = 'Inactive';
            }
        }
        if(otherActiveSprints.size() > 0){
            update otherActiveSprints;
        }
    }
}